name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3.2

    # Restore and build
    - name: Restore and build
      run: msbuild src /t:Restore,Build /p:Configuration=$env:Configuration /p:DeployExtension=false
      env:
        Configuration: ${{ matrix.configuration }}

    # Run unit tests
    - name: Run unit tests
      run: dotnet test --no-build test\ColumnGuideTests\ColumnGuideTests.csproj --configuration $env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Upload the VSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload build artifact (VSIX)
      uses: actions/upload-artifact@v4.3.0
      with:
        name: VSIX Package ($env)
        path: src/VSIX/bin/**/*.vsix
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Upload build artifact (VSIX)
      uses: actions/upload-artifact@v4.3.0
      with:
        name: VSIX Package ($env, Dev 17)
        path: src/VSIX_Dev17/bin/**/*.vsix
      env:
        Configuration: ${{ matrix.configuration }}
